### ISSUE TITLE
Async/await TODO

### ISSUE THREAD

**Issue by pimeys** [prisma/tiberius#12]
Things to do until hitting the publish button for the async/await version of Tiberius. Started from a state where the transportation and quite a many basic types already work and are usable.

- [x] `date`/`datetimeoffset`/`datetime2`/`smalldatetime`/`datetime`/`time` types
- [x] `text`/`ntext` types
- [x] `binary`/`varbinary`
- [x] `image`
- [x] `xml`
- [x] User-defined types
- [ ] Transaction system. Maybe the connection should finally be `Arc<Mutex<Connection>>` in the `Client`, so a transaction can roll back on `Drop` if needed. (https://github.com/prisma/tiberius/issues/28)
- [x] Guid type
- [x] Execute doesn't really need to be a stream, The results should be collected to a vector for better error handling and provided as an iterator or using the `total` method.
- [x] ADO.NET connection strings
- [x] Testing SSPI windows login (on windows)
- [x] Windows authentication
- [x] Testing SQL browser mode (on windows)
- [x] Testing TLS
- [x] Testing Azure
- [ ] Builder and connection should handle all possible features and options.
- [x] AppVeyor setup for this fork.
- [x] Work on tokio, async-std and smol (https://github.com/prisma/tiberius/issues/29)
- [x] Fix `numeric` handling (https://github.com/prisma/tiberius/issues/31)

**Comment by esheppa** [comment]
Hi @pimeys I've made a fork and had a start at the last two items in the list.
In the 0.3 version there was the following type to conditionally wrap TLS
```rust
  /// wraps written/read data into PRELOGIN packets
    pub struct TlsTdsWrapper<S> {
        stream: S,
        /// whether to wrap written/read data into prelogin packets (required for the handshake)
        pub wrap: bool,
        wr: Vec<u8>,
        rd: Vec<u8>,
        bytes_left: usize,
    }
```
I've attempted to do the same in this version of the code in the tls module, wrapping the `TcpStream` and and then implementing `AsyncRead` and `AsyncWrite`, and inside those removing/adding the TDS prelogin headers. It is tricky because the `connect` function from the TLS crates (tokio-tls/tokio-rustls) takes an argument that has to implement `AsyncRead` and `AsyncWrite` and  this seems to be the only way to get at the messages it sends and wrap them in TDS prelogin. Do you think that I'm on the right track here, or is there a better way to do this?

It seems nice to use `connection::send` and `codec::collect_from` but I'm not sure how to consume those inside the `AsyncRead` and `AsyncWrite` impls

**Comment by pimeys** [comment]
Hmm, I don't think I quite follow you. Did you try the current implementation with TLS and it didn't work?

What it currently does is it uses a plain TCP connection for prelogin, then a TLS handshake and from there on continues the process.

What kind of SQL Server setup you use to enable TLS? I could try to see this myself too on Monday as my next work item, due to working TLS and Azure being extremely important for us too.

**Comment by esheppa** [comment]
Yes I initially set up an Azure SQL database and then set up environment variables and ran the tests however I was getting a "Connection reset by peer" message. As a next step I added in rustls as I thought that I might get a different error message from that however it ended up with the same "Connection reset by peer". (However I may just have something wrong in my setup - have you been able to get it working with TLS?)

After those steps I went back and re-read the section in the protocol docs ([tds-ssl](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/60f56408-0188-4cd5-8b90-25c6f2423868)) and had another look at the 0.3 version, it seems that TDS requires something quite tricky if a TLS connection is desired:
1. First the TLS handshake is completed with each message wrapped in a TDS prelogin message
2. Once the handshake is complete, the new `TlsStream<TcpStream>` should then be used such that all further TDS packets are sent encrypted inside TLS packets.

In tokio-tls/rustls there is a `connect` function which takes the initial `TcpStream` and returns a wrapped `TcpStream` which I assume would then encrypt all data written/decrypt all data read from it, however the `connect` function handles the handshake process internally, so I attempted to use the pattern from 0.3 where a newtype implements AsyncRead and AsyncWrite to capture the handshake messages and wrap them in prelogin message. Once that process is complete the `wrap` field would be set to `true` and then the newtype would just pass through all read/write calls. 

To do this I used some parts of the internals of the `connection::send` function to try and get the headers 

excerpt from tls.rs:
```rust

#[derive(Debug)]
pub struct TlsTdsWrapper {
    stream: TcpStream,
    bytes_to_write: Vec<u8>,
    bytes_to_read: Vec<u8>,
    bytes_read: usize,
    bytes_written: usize,
    wrap: bool,
    packet_size: usize,
    packet_header: codec::PacketHeader,
}

impl AsyncWrite for TlsTdsWrapper
{
    fn poll_write(
        mut self: Pin<&mut Self>,
        cx: &mut task::Context,
        buf: &[u8]
    ) -> Poll<io::Result<usize>> {
        let should_wrap = self.wrap;
        let mut header = self.packet_header.clone();
        let mut wtr = self.get_mut();
        let p = Pin::new(&mut wtr.stream);
        if should_wrap {
            let payload = bytes::BytesMut::from(buf);

            header.set_status(codec::PacketStatus::NormalMessage);
            let packet = codec::Packet::new(header, payload);

            let mut write_buf = bytes::BytesMut::new();
            packet.encode(&mut write_buf).unwrap();

            dbg!(&write_buf);
            p.poll_write(cx, &write_buf)
        } else {
            p.poll_write(cx, &buf)
        }
    }
//
}

pub enum MaybeTlsStream {
    Raw(TcpStream),
    #[cfg(feature = "tls")]
    Tls(tokio_tls::TlsStream<TlsTdsWrapper>),
    #[cfg(feature = "rust-tls")]
    RustTls(tokio_rustls::client::TlsStream<TlsTdsWrapper>),
}
```

usage in builder.rs: (please don't mind the `unwrap`/`dbg!`, still in process :D )
```rust
 #[cfg(feature = "rust-tls")]
    pub(crate) async fn tls_handshake(
        self,
        ssl: EncryptionLevel,
        trust_cert: bool,
        domain: &str,
    ) -> crate::Result<Self> {
        if ssl != EncryptionLevel::NotSupported {

            let mut config = rustls::ClientConfig::new();
            config.versions = vec!(rustls::ProtocolVersion::TLSv1_2);
            config.ciphersuites = vec!(&rustls::ALL_CIPHERSUITES[7]);
            config.root_store.add_server_trust_anchors(&webpki_roots::TLS_SERVER_ROOTS);

            let connector = tokio_rustls::TlsConnector::from(Arc::new(config));
            let dns_ref = webpki::DNSNameRef::try_from_ascii_str(&domain).expect("Invalid DNS name");
            let ps = self.get_packet_size();
            let ph = self.get_prelogin_packet_header(ssl);

            let stream = match self.transport.into_inner() {
                MaybeTlsStream::Raw(tcp) => { 
                    let wrapped = TlsTdsWrapper::new(ps, ph, tcp);
                    let s = connector.connect(dns_ref, wrapped).await;
                    dbg!(&s);
                    s.unwrap()
                },
                _ => unreachable!(),
            };

            let transport = Framed::new(MaybeTlsStream::RustTls(stream), PacketCodec);

            Ok(Self {
                transport,
                context: self.context,
                flushed: false,
                buf: BytesMut::new(),
            })
        } else {
            Ok(self)
        }
    }
```

**Comment by pimeys** [comment]
This needs some proper investigation, I'll spend the whole tomorrow to it, but meanwhile if you have time, please see if you can understand a bit more what happens here.

So you did not get into the `login` step at all? The login should set `AZURESQLSUPPORT` feature on, so that might be the next step after TLS works.

**Comment by esheppa** [comment]
Ok I'll have another look tomorrow as I think the `AsyncWrite` part is quite close to working but it may be missing some part of the TDS protocol.



> So you did not get into the `login` step at all? The login should set `AZURESQLSUPPORT` feature on, so that might be the next step after TLS works.

Correct, I was getting the "Connection reset by peer" error and not reaching the login stage. I think this is reaching the sink on the right side of the below diagram as it says that if it recieves a "tls/ssl packet that is structuarly invalid" then it will close the connection, specifically on this page [tds-workflow](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/ce1cef02-f43c-4e37-a190-aaa444b96360) where it 

![tds-workflow](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/ms-tds_files/image008.png)

An alternative option which I could look into is implementing the handshake explicitly, using the implementation in tokio-rustls as a start, that would make it easier to get the TLS messages as a `Encode<BytesMut>` and send them using the existing send function. This seems possible to be done as the two exchanges as part of the handshake are detailed here [tds-sslhandshake](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/5a9d49b8-d1c4-4ff5-8f65-76dc924f5c4d) however it may not be preferable to duplicate the functionality of the tls-adapter crates. 
```rust
   pub(crate) async fn send<E>(&mut self, mut header: PacketHeader, item: E) -> crate::Result<()>
    where
        E: Sized + Encode<BytesMut>,
```

**Comment by pimeys** [comment]
I just created a discord channel to our server if you'd like to join. I think this is not that hard in the end, let's figure it out tomorrow.

https://discord.gg/jxC2vH

**Comment by pimeys** [comment]
What was wrong in the TLS is the SQL Server expects TDS packets also in the handshake. This pull request fixes the issue and TLS works on Azure SQL with TLS on:

https://github.com/prisma/tiberius/pull/17

**Comment by pimeys** [comment]
I was able to get Windows authentication methods working on my Windows VM yesterday. So Windows login by providing a username and password works, and SSPI which uses your current account credentials works.

I tried to understand how to connect using the SQL Browser, but I had no luck even getting it working with the old Tiberius code.

**Comment by pimeys** [comment]
Also something I'd like to think for XML is how hard would it be to map the server XML to a serde struct? Such as using UDT's, XML could also just `Serialize`/`Deserialize` directly from the database.

**Comment by pimeys** [comment]
# User-defined types

I was planning today to write support for User-defined types (UDT). What I thought they were is something like Point(1, 2), that I can insert to tables and serialize/deserialize.Actually there are three kinds of UDTs:

## Aliases

```sql
CREATE TYPE Age FROM int;
```
The most basic UDT. You define it to inherit from one of the standard types, and you can use it in a table. It seems we already support them, here you map the return value as i32 and continue your life.

## Table types

```sql
CREATE TYPE Cat AS TABLE (name nvarchar(max), age int);
```

A more complex UDT. The biggest restriction with a table type is how one cannot use them in tables. One can use them as a parameter to a stored procedure:

```sql
CREATE PROCEDURE GetAges(@CatParm Cat READONLY) AS SELECT age FROM @CatParm
```

When having less than 1000 items, it is faster to create a list of items instead of a temporary table. The list can hold items defined with the type. This list works like a table and doesn't require modifications to Tiberius.

## Assembly types

The third UDT is heavily bound to the Common Language Runtime (CLR) from Microsoft. The type is defined with a given dll library assembly and holds methods and data that can be queried from the database. The main function is to execute code inside the SQL Server.

From Tiberius, we cannot query the assembly UDTs as a type, but we can call its methods, that should return the basic types we can map to normal Rust values.

## Summary

Everything should just work now. We need more user input how the UDTs are used and if we need to provide more support than what we have now. Putting a cross here to the list.

**Comment by pimeys** [comment]
Support for `image` and `xml` types were added today.

- https://github.com/prisma/tiberius/pull/27
- https://github.com/prisma/tiberius/pull/26

Next thing I'm doing is proper server option handling.

**Comment by benjaminweb** [comment]
Will you support a connection pool to use it like other DB interfaces with rocket? https://rocket.rs/v0.4/guide/state/#databases

**Comment by pimeys** [comment]
This will be part of Quaint so it must work well with connection pools.

We use mobc as a pool and it should be quite easy to write a manager for it...

-------- Original Message --------

**Comment by pimeys** [comment]
Decided the transaction API and FeatureExt options do not stop us releasing a 0.4.0. Please see the corresponding tickets if needing support for certain extensions or maybe if needing a higher-level API for transactions.
